name: Xpens

options:
  bundleIdPrefix: com.xpens
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: "0.9.19"

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"

schemes:
  Xpens:
    build:
      targets:
        Xpens: all
        XpensTests: [test]
        XpensUITests: [test]
    test:
      targets:
        - XpensTests
        - XpensUITests

targets:
  Xpens:
    type: application
    platform: iOS
    sources:
      - Xpens
    dependencies:
      - package: ZIPFoundation
    settings:
      base:
        DEVELOPMENT_TEAM: UM8YA6TAD4
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.xpens.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "7"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_NSCameraUsageDescription: "We need camera access to scan receipts"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "We need photo library access to attach receipt images"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: false
        CODE_SIGN_ENTITLEMENTS: Xpens/Xpens.entitlements

  XpensTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - XpensTests
    dependencies:
      - target: Xpens
      - package: ZIPFoundation
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.xpens.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Xpens.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Xpens"
        BUNDLE_LOADER: "$(TEST_HOST)"

  XpensUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - XpensUITests
    dependencies:
      - target: Xpens
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.xpens.app.uitests
        TEST_TARGET_NAME: Xpens
